name: Build dmnd-client binaries for Linux and macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Linux Binary
        run: cargo build --release

      - name: Rename Linux Binary
        run: mv target/release/dmnd-client dmnd-client-linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: dmnd-client-linux

  build-macos:
    name: Build macOS Binary
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build macOS Binary
        run: cargo build --release

      - name: Rename macOS Binary
        run: mv target/release/dmnd-client dmnd-client-macos

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: dmnd-client-macos

  build-windows:
    name: Build Windows Binary
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Windows Binary
        run: cargo build --release

      - name: Rename Windows Binary
        run: move target\release\dmnd-client.exe dmnd-client-windows.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: dmnd-client-windows.exe

  add-checksum:
    name: Create Checksums
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: binaries
          merge-multiple: true

      - name: Generate checksums
        working-directory: binaries
        run: sha256sum dmnd-client-linux dmnd-client-macos dmnd-client-windows.exe > checksums.sha256

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: binaries/checksums.sha256
